ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'STATE_MANAGER';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'DISTRICT_HEAD';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'CITY_REPORTER';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'CONSTITUENCY_REPORTER';
